remote_theme: pages-themes/cayman@v0.2.0
title: [ğ”ğ”¢ğ”° ğ”±ğ”¢ğ”ªğ”­ğ”° ğ”¡ğ”¢ â„­ğ”ğ”¯ğ”±ğ”¢ğ”¯]
description: [ğ”ğ”¢ğ”° ğ”±ğ”¢ğ”ªğ”­ğ”° ğ”¡ğ”¢ â„­ğ”ğ”¯ğ”±ğ”¢ğ”¯ is a platform that hopes to post every week a article about everyday struggles, along with questions and opinions of the main auther, â„­ğ”ğ”¯ğ”±ğ”¢ğ”¯]
show_downloads: [false]
